Meter/Models/Batch.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int BatchNo { get; set; }
        public Nullable<int> Custid { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public Nullable<int> Totaldone { get; set; }
        public Nullable<byte> printed { get; set; }
        public string BatchStatus { get; set; }
        public string Notes { get; set; }
    }
}

Meter/Controllers/BatchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Meter.Models;
using Meter.ViewModels;

namespace Meter.Controllers
{
    public class BatchesController : Controller
    {
        private PrecisionMeterEntities db = new PrecisionMeterEntities();
        
        //[Authorize]
        // GET: Batches
        public ActionResult Index() 
        {

            return View(db.Batches.ToList()); //.OrderByDescending(x => x.BatchNo));
        }

        public ActionResult GetBatchMeters(int batchno)
        {
            var x = db.Repairs.Where(r => r.Batchno == batchno)
                .Join(db.Customers,
                      c => c.Custid,
                      o => o.Custid,
                      (c, o) => new
                      {
                          Company = o.Company,
                          sysid = c.sysid,
                          Batchno = c.Batchno,
                          Custid = c.Custid,
                          mfgnum = c.mfgnum,
                          conum = c.conum,
                          conumandmfgnum = c.conumandmfgnum,
                          Mfgsize = c.Mfgsize,
                          Afpopen = c.Afpopen,
                          Afpcheck = c.Afpcheck,
                          Afperro = c.Afperro,
                          TextMessage1 = c.TextMessage1,
                          Message1 = c.Message1,
                          Alopen = c.Alopen,
                          Alcheck = c.Alcheck,
                          Alerror = c.Alerror,
                          Pdate = c.Pdate,
                          Textmessage2 = c.Textmessage2,
                          Message2 = c.Message2,
                          Pby = c.Pby,
                          Rft = c.Rft,
                          Irat = c.Irat,
                          Irbt = c.Irbt,
                          Remarks = c.Remarks,
                          Statue = c.Statue

                      }).ToList();


            return Json(x.ToList(), JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetBatchList()
        {
            //return View(db.Customers.Include(d => d.Repairs).ToList());
            
            var x = (from obj in db.Batches select new { BatchNo = obj.BatchNo, Custid = obj.Custid, BatchDate = obj.BatchDate, Totaldone = obj.Totaldone, Printed = obj.printed }).ToList().OrderByDescending(b => b.BatchNo);
            return Json(x.ToList().OrderByDescending(b => b.BatchNo), JsonRequestBehavior.AllowGet);
        }
        // GET: Batches/Details/5

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Batch batch = db.Batches.Find(id);
            if (batch == null)
            {
                return HttpNotFound();
            }
            return View(batch);
        }

        // GET: Batches/Create
        public ActionResult Create()
        {
           
            var customers = db.Customers.ToList().OrderBy(x => x.Company);
            ViewData["Cust"] = customers;
            return View();
        }

        public ActionResult AddMeter(string id)
        {
            ViewBag.Custid = new SelectList(db.Customers, "Custid", "Company");
            ViewBag.BatchNo = id;
            ViewBag.AFM = db.MeterOptions.ToList().Where(x => x.Type == "AFM");
            return View();
        }


        // POST: Batches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BatchNo,Custid,BatchDate,Totaldone,printed,BatchStatus,Notes")] Batch batch)
        {
            if (ModelState.IsValid)
            {
                db.Batches.Add(batch);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(batch);
        }

        [HttpPost]
        public void InsertBatch(string custId)
        {

        }

        // GET: Batches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Batch batch = db.Batches.Find(id);
            if (batch == null)
            {
                return HttpNotFound();
            }
            return View(batch);
        }

        // POST: Batches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BatchNo,Custid,BatchDate,Totaldone,printed,BatchStatus,Notes")] Batch batch)
        {
            if (ModelState.IsValid)
            {
                db.Entry(batch).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(batch);
        }

        // GET: Batches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Batch batch = db.Batches.Find(id);
            if (batch == null)
            {
                return HttpNotFound();
            }
            return View(batch);
        }

        // POST: Batches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Batch batch = db.Batches.Find(id);
            db.Batches.Remove(batch);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Meter/Views/Batches/AddMeter.cshtml
@model Meter.Models.Repair

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
   // Model.Batchno = Convert.ToInt16(ViewBag.BatchNo);
    var batchno = Convert.ToInt32(ViewBag.BatchNo);
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Repair</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Batchno, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-1">
            @Html.EditorFor(model => model.Batchno, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Batchno, "", new { @class = "text-danger", @Value = ViewBag.BatchNo })
        </div>
        @Html.LabelFor(model => model.Custid, "Custid", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.DropDownList("Custid", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Custid, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.mfgnum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.mfgnum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mfgnum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.conum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.conum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.conum, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.conumandmfgnum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.conumandmfgnum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.conumandmfgnum, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Mfgsize, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Mfgsize, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mfgsize, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Afpopen, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Afpopen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Afpopen, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Afpcheck, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Afpcheck, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Afpcheck, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Afperro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Afperro, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Afperro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Show Message", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            <div class="checkbox">
                @Html.EditorFor(model => model.TextMessage1)
                @Html.ValidationMessageFor(model => model.TextMessage1, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.LabelFor(model => model.Message1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.EditorFor(model => model.Message1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Message1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Alopen, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Alopen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Alopen, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Alcheck, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Alcheck, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Alcheck, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Alerror, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Alerror, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Alerror, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Textmessage2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            <div class="checkbox">
                @Html.EditorFor(model => model.Textmessage2)
                @Html.ValidationMessageFor(model => model.Textmessage2, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.LabelFor(model => model.Message2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.EditorFor(model => model.Message2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Message2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Pby, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Pby, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Pby, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Rft, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Rft, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rft, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Irat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Irat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Irat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Irbt, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Irbt, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Irbt, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Statue, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Statue, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Statue, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Pdate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            @Html.EditorFor(model => model.Pdate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Pdate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @*@Html.ActionLink("Back to List", "Edit")*@
    @Html.ActionLink("Back to list", "Edit","Batches",new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Meter/Views/Batches/Create.cshtml
@model Meter.Models.Batch

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
@{ 
    var notedate = DateTime.Now;
    var notes = $"Batch Inserted by {User.Identity.Name} on {notedate}";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Batch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Company", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @*@Html.DropDownListFor("SelectedEmployee", new SelectList((System.Collections.IEnumerable)ViewData["Cust"], "Custid", "Company"), new { @class = "form-control" })*@
                @Html.DropDownListFor(model => model.Custid, new SelectList((System.Collections.IEnumerable)ViewData["Cust"],"Custid","Company"), new { @class = "form-control" })
            </div>
            @Html.Label("Date Entered", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.BatchDate,  new { @Value = @DateTime.Now.ToShortDateString(), @class = "form-control" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.Label("Total Meters", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Totaldone, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.Totaldone, "", new { @class = "text-danger" }*@
                @*@Html.TextBoxFor(model => model.Totaldone, new { @Value = 0, @class = "form-control" })*@
            </div>
            @Html.Label("Printed", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @*@Html.EditorFor(model => model.printed, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.printed, "", new { @class = "text-danger" })*@
                @Html.TextBoxFor(model => model.printed, new { @Value = "", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @*@Html.EditorFor(model => model.BatchStatus, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BatchStatus, "", new { @class = "text-danger" })*@
                @Html.TextBoxFor(model => model.BatchStatus, new { @Value = "Active", @class = "form-control" })
            </div>
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @*@Html.TextAreaFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })*@
                @Html.TextBoxFor(model => model.Notes, new { @Value = notes, @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Meter/Views/Batches/Delete.cshtml
@model Meter.Models.Batch

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Batch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Custid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Custid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BatchDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BatchDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Totaldone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Totaldone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.printed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.printed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BatchStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BatchStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Meter/Views/Batches/Details.cshtml
@model Meter.Models.Batch

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Batch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Custid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Custid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BatchDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BatchDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Totaldone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Totaldone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.printed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.printed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BatchStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BatchStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BatchNo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Meter/Views/Batches/Edit.cshtml
@model Meter.Models.Batch

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Batch</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Batch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BatchNo)

        <div class="form-group">
            @Html.LabelFor(model => model.Custid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Custid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Custid, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.BatchDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.BatchDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BatchDate, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Totaldone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Totaldone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Totaldone, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.printed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.printed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.printed, "", new { @class = "text-danger" })
            </div>        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BatchStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.BatchStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BatchStatus, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<hr />
@Html.ActionLink("Add Meters to Batch", "AddMeter", null, htmlAttributes: new { @class = "btn btn-info" })
<div class="container">
    <br />
    <div style="width:100%; margin:0 auto;">
        <table id="meters" class="table table-striped table-bordered table-responsive nowrap" cellspacing="0" ; style="width:100%">
            <thead>
                <tr>
                    <th>sysid</th>
                    <th>Batchno</th>
                    <th>Custid</th>
                    @*<th>Mfg#</th>
                        <th>Co#</th>
                        <th>conumandmfgnum</th>*@
                    <th>Mfg Size</th>
                    <th>Afp Open</th>
                    <th>Afp Check</th>
                    <th>Afp Error</th>
                    <th>Al Open</th>
                    <th>AL Check</th>
                    <th>Al Error</th>
                    <th>PDate</th>
                    @*<th>Pby</th>
                    <th>Rft</th>*@
                        @*<th>Irat</th>
                        <th>Irbt</th>
                        <th>Remarks</th>
                        <th>Statue</th>*@
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<!--<div id="GetMeters" class="btn btn-default">Get Meters</div>-->
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")

Meter/Views/Batches/Index.cshtml
@model IEnumerable<Meter.Models.Batch>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Batch Records</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="container">
    <br />
    <div style="width:90%; margin:0 auto;">
        <table id="batchGrid" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0" ; style="width:100%">
            <thead>
                <tr>
                    <th>Batch#</th>
                    <th>Custid</th>
                    <th>Batch Date</th>
                    <th>Total Done</th>
                    <th>Printed</th>
                    @*<th>Active</th>*@
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/DataTables/datatables.js"></script>
<script src="~/Scripts/moment.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
@*<script src="~/Scripts/batch.js"></script>*@